### ISSUE TITLE
视频文件存在多版本使用Extract MediaInfo扫描媒体信息报错

### ISSUE THREAD

**Issue by sunbroke555** [sjtuross/StrmAssistant#33]
问题：
strm视频存在多个版本时使用Extract MediaInfo扫描媒体信息仅能扫到默认版本信息.
另外一个版本会报错且每次运行此任务都进行扫描尝试
错误日志如下：

2024-11-22 14:02:25.507 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第48集.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-11-22 14:02:25.517 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第 48 集 - WEB-DL - WEB.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-11-22 14:02:29.800 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-11-22 14:02:29.803 Info HttpClient: GET https://api4.thetvdb.com/v4/episodes/8401928/extended?meta=translations
2024-11-22 14:02:30.068 Info Strm Assistant: MediaInfoExtract - Progress 50/208 - Task 52: /115link/link/国产剧/御赐小仵作 (2021) {tmdbid=124595}/Season 1/御赐小仵作 - S01E01 - 第1集.strm
2024-11-22 14:02:30.075 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E47 - 第 47 集 - WEB-DL - WEB.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-11-22 14:02:30.081 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E47 - 第47集.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-11-22 14:02:33.254 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-11-22 14:02:33.254 Error App: Error in ffprobe
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.10.55+ (root@build7) (x86_64-pc-linux-gnu-gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.38) #69057 SMP Fri Jan 12 17:02:57 CST 2024
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: /config
	Application path: /system
	Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "**http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第 48 集 - WEB-DL - WEB.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data**
	ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
	  built with gcc 10.3.0 (crosstool-NG 1.25.0)
	[http @ 0x1862300] HTTP error 403 Forbidden
	    Last message repeated 1 times
	[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1861940] moov atom not found
	http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第 48 集 - WEB-DL - WEB.mp4: Invalid data found when processing input
	
	
	{
	
	}
	   at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
	   at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	
2024-11-22 14:02:33.265 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-11-22 14:02:33.265 Error App: Error in ffprobe
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.10.55+ (root@build7) (x86_64-pc-linux-gnu-gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.38) #69057 SMP Fri Jan 12 17:02:57 CST 2024
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: /config
	Application path: /system
	Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第 48 集 - WEB-DL - WEB.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
	ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
	  built with gcc 10.3.0 (crosstool-NG 1.25.0)
	[http @ 0x92e300] HTTP error 403 Forbidden
	    Last message repeated 1 times
	[mov,mp4,m4a,3gp,3g2,mj2 @ 0x92d940] moov atom not found
	**http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰 (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第 48 集 - WEB-DL - WEB.mp4: Invalid data found when processing input**
	
	
	{
	
	}
	   at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
	   at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()

此报错文件路径复制到浏览器能正常打开播放

**Comment by sunbroke555** [comment]
路径打开视频截图（确保路径无误）：
![Uploading 72cb78b8-67da-4c47-b54a-44b3f18c43f0.png…]()

**Comment by sjtuross** [comment]
从日志看，插件已经正确派发了2个任务，下面2条ffprobe日志里的路径也是正确的。出错是因为`HTTP error 403 Forbidden`，自己排查alist的问题吧。

```
2024-11-22 14:02:25.507 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "[http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰](http://192.168.0.105:5244/d/115/video/%E5%9B%BD%E4%BA%A7%E5%89%A7/%E9%95%BF%E5%AE%89%E5%8D%81%E4%BA%8C%E6%97%B6%E8%BE%B0) (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第48集.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-11-22 14:02:25.517 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "[http://192.168.0.105:5244/d/115/video/国产剧/长安十二时辰](http://192.168.0.105:5244/d/115/video/%E5%9B%BD%E4%BA%A7%E5%89%A7/%E9%95%BF%E5%AE%89%E5%8D%81%E4%BA%8C%E6%97%B6%E8%BE%B0) (2019) {tmdbid=90768}/Season 1/长安十二时辰 - S01E48 - 第 48 集 - WEB-DL - WEB.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
```
