### ISSUE TITLE
不支持提取视频截图TS格式的视频文件吗 报错 Error QuickSingleImageExtractor: ProcessRun 'quick-extract-image' Error Output:

### ISSUE THREAD

**Issue by 907739769** [sjtuross/StrmAssistant#36]
2024-12-01 22:17:41.602 Error QuickSingleImageExtractor: ProcessRun 'quick-extract-image' Error Output:
	ffmpeg version 5.1-emby_2023_06_25 Copyright (c) 2000-2022 the FFmpeg developers and softworkz for Emby LLC
	  built with gcc 10.3.0 (crosstool-NG 1.25.0)
	Execution Date: 2024-12-01 22:07:41
	-vsync is deprecated. Use -fps_mode
	Passing a number to -vsync is deprecated, use a string argument as described in the manual.
	[mpegts @ 0xfa44c0] Invalid timestamps stream=0, pts=3850415, dts=3853014, size=161796
	[mpegts @ 0xfa44c0] Invalid timestamps stream=0, pts=3857613, dts=3860212, size=162091
	[mpegts @ 0xfa44c0] Invalid timestamps stream=0, pts=3864811, dts=3867410, size=165954
	[mpegts @ 0xfa44c0] Invalid timestamps stream=0, pts=3872009, dts=3874608, size=143698
	[mpegts @ 0xfa44c0] Invalid timestamps stream=0, pts=3879207, dts=3881806, size=151459
	[http @ 0xfa4e80] HTTP error 403 Forbidden
	Input #0, mpegts, from 'http://192.168.31.89:5244/d/115网盘/影视/pt/电视剧/欧美剧/All That Glitters.Complete.HDTV.1080p.H264-OneHD/[壹高清]金色大道.All That Glitters.Ep29.HDTV.1080p.H264-OneHD.ts':
	  Duration: 00:00:02.37, start: 42.733722, bitrate: 11976597 kb/s
	  Program 1 
	  Stream #0:0[0x44]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m, progressive), 1920x1080 [SAR 1:1 DAR 16:9], Level 40, 25 fps, 25 tbr, 90k tbn, Start-Time 42.742s
	  Stream #0:1[0x45]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s, Start-Time 42.734s
	Stream mapping:
	  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
	Press [q] to stop, [?] for help
	[mpegts @ 0xfa44c0] Invalid timestamps stream=0, pts=3850415, dts=3853014, size=161796
	[swscaler @ 0x14e0480] [swscaler @ 0x15abf40] deprecated pixel format used, make sure you did set range correctly
	[swscaler @ 0x14e0480] [swscaler @ 0x150a580] deprecated pixel format used, make sure you did set range correctly
	[swscaler @ 0x14e0480] [swscaler @ 0x14fc3c0] deprecated pixel format used, make sure you did set range correctly
	[swscaler @ 0x14e0480] [swscaler @ 0x15abf40] deprecated pixel format used, make sure you did set range corr
2024-12-01 22:17:41.604 Error App: Error in Image Capture
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #72806 SMP Thu Sep 5 13:44:44 CST 2024
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: Error running ffmpeg quick-extract-image for "http://192.168.31.89:5244/d/115网盘/影视/pt/电视剧/欧美剧/All That Glitters.Complete.HDTV.1080p.H264-OneHD/[壹高清]金色大道.All That Glitters.Ep29.HDTV.1080p.H264-OneHD.ts" - Command: -skip_list 273 -f mpegts -threads 1 -i "http://192.168.31.89:5244/d/115网盘/影视/pt/电视剧/欧美剧/All That Glitters.Complete.HDTV.1080p.H264-OneHD/[壹高清]金色大道.All That Glitters.Ep29.HDTV.1080p.H264-OneHD.ts" -an -sn -update 1 -vsync 0 -f image2 "/config/cache/temp/c1b1bc6d-4414-457f-9f73-91d6af5110eb.jpg"
	   at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractorBase.RunExtraction(String inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 protocol, Nullable`1 streamIndex, Nullable`1 threedFormat, Nullable`1 startOffset, Nullable`1 interval, String targetDirectory, String targetFilename, Nullable`1 maxWidth, Boolean enableThumbnailFilter, CancellationToken cancellationToken)
	   at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractionManager.ExtractImageInternal(ReadOnlyMemory`1 inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 streamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useThumbNailFilter, CancellationToken cancellationToken)
	   at Emby.Server.MediaEncoding.ImageExtraction.ImageExtractionManager.ExtractImage(ReadOnlyMemory`1 inputPath, Nullable`1 container, MediaStream videoStream, Nullable`1 streamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
	   at Emby.Providers.MediaInfo.VideoImageProvider.GetImage(BaseMetadataResult itemResult, ImageType type, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseMetadataResult itemResult, IDynamicImageProvider provider, Boolean providerReportsChanges, ImageRefreshOptions refreshOptions, Boolean replaceAllImages, TypeOptions savedOptions, LibraryOptions libraryOptions, List`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()

**Comment by 907739769** [comment]
应该是网盘风控了
